import type { CriticalFlag, LegalCategory, RecommendedAction, Severity } from "./types.js";

export interface Detector {
  clauseType: string;
  category: LegalCategory;
  pattern: RegExp;
  severity: Severity;
  criticalFlag?: CriticalFlag;
  confidence: number;
  summary: string;
  whyItMatters: string;
  legalExposure: string;
  companyPosition?: string;
  recommendedAction: RecommendedAction;
  requiresExternalCounsel: boolean;
}

/**
 * Keyword/pattern detectors used by MockLegalLLMClient. Each one is grounded in a real
 * clause-type from agents/skills/lawyer.md's Assessment checklist, and only fires — and
 * therefore only ever produces a cited finding — when matching text actually exists in
 * the document. Two flags from AUTOMATIC_CRITICAL_FLAGS (MANDATORY_REQUIREMENT_NOT_MET,
 * MISSING_LICENSE) are deliberately not wired to any detector here: judging whether a
 * requirement is unmet needs the bidder's own company profile, which this agent doesn't
 * have access to — fabricating that judgment from document text alone would violate the
 * "never silently guess" principle (TENDER_ASSISTANT.md §3.4).
 */
export const DETECTORS: Detector[] = [
  // 1. Payment & cash flow
  {
    clauseType: "retention_percentage",
    category: "payment_cash_flow",
    pattern: /\bretent(?:ion|age)\b/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Retention/retainage clause found.",
    whyItMatters: "Retention ties up cash until release conditions are met, affecting working capital.",
    legalExposure: "Cash flow exposure until retention release conditions are satisfied.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "pay_when_paid",
    category: "payment_cash_flow",
    pattern: /pay[-\s]when[-\s]paid|pay[-\s]if[-\s]paid/i,
    severity: "high",
    confidence: 0.75,
    summary: "Contingent (pay-when-paid / pay-if-paid) payment clause found.",
    whyItMatters: "Ties the bidder's payment to a third party's payment, shifting the owner's credit risk downstream.",
    legalExposure: "Payment may be withheld indefinitely if the paying party upstream doesn't pay.",
    recommendedAction: "negotiate_before_bid",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "advance_payment",
    category: "payment_cash_flow",
    pattern: /advance payment|mobili[sz]ation advance/i,
    severity: "low",
    confidence: 0.55,
    summary: "Advance/mobilization payment clause found.",
    whyItMatters: "May require a bond to secure repayment — check the bonding cost against the advance amount.",
    legalExposure: "Advance repayment obligation, typically secured by an on-demand bond.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 2. Damages & liability
  {
    clauseType: "liquidated_damages",
    category: "damages_liability",
    pattern: /liquidated damages/i,
    severity: "high",
    confidence: 0.7,
    summary: "Liquidated damages clause found — confirm rate and cap.",
    whyItMatters: "LD rate and cap determine schedule-risk exposure; an uncapped LD clause is unbounded downside.",
    legalExposure: "Exposure depends on stated daily/weekly rate and cap — verify both are present.",
    companyPosition: "Standard company policy requires an LD cap of 10% of contract value or less.",
    recommendedAction: "negotiate_before_bid",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "unlimited_liability",
    category: "damages_liability",
    pattern: /(without\s+(?:any\s+)?limit(?:ation)?\s+(?:as\s+to|of|on)\s+liability|no\s+limit(?:ation)?\s+(?:on|of)\s+liability|unlimited\s+liability)/i,
    severity: "critical",
    criticalFlag: "UNLIMITED_LIABILITY",
    confidence: 0.8,
    summary: "Language indicating uncapped overall liability.",
    whyItMatters: "An uncapped liability clause creates unbounded downside regardless of contract value.",
    legalExposure: "Unbounded — no contractual ceiling on overall liability.",
    companyPosition: "Standard company policy requires an overall liability cap tied to contract value.",
    recommendedAction: "escalate_to_counsel",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "consequential_damages_exclusion",
    category: "damages_liability",
    pattern: /consequential damages|indirect damages/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Consequential/indirect damages clause found — confirm it is mutual.",
    whyItMatters: "A one-sided consequential-damages exclusion (owner protected, contractor not) shifts risk asymmetrically.",
    legalExposure: "Depends on mutuality — verify both parties are equally protected.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 3. Indemnification & insurance
  {
    clauseType: "unlimited_indemnity",
    category: "indemnification_insurance",
    pattern: /indemnif(?:y|ication)(?:[^.]{0,80})(?:without limit|unlimited|no cap)/i,
    severity: "critical",
    criticalFlag: "UNLIMITED_INDEMNITY",
    confidence: 0.75,
    summary: "Indemnification language with no stated cap.",
    whyItMatters: "Uncapped indemnity obligations create unbounded exposure independent of any liability cap elsewhere in the contract.",
    legalExposure: "Unbounded — no contractual ceiling on indemnification obligations.",
    companyPosition: "Standard company policy requires indemnities to be capped and mutual.",
    recommendedAction: "escalate_to_counsel",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "broad_form_indemnity",
    category: "indemnification_insurance",
    pattern: /indemnify(?:[^.]{0,40})any and all claims/i,
    severity: "high",
    confidence: 0.65,
    summary: "Broad-form indemnity ('any and all claims') found.",
    whyItMatters: "Broad-form indemnities can extend beyond the indemnifying party's own negligence.",
    legalExposure: "Potential exposure to claims not caused by the bidder's own negligence.",
    recommendedAction: "negotiate_before_bid",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "insurance_requirement",
    category: "indemnification_insurance",
    pattern: /(contractor'?s all risk|professional indemnity insurance|public liability insurance|employer'?s liability insurance|CAR\/EAR)/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Required insurance type/limit specified.",
    whyItMatters: "Insurance requirements affect bid cost and must be confirmed as obtainable at the stated limits.",
    legalExposure: "Cost and availability risk if required cover/limits exceed current policies.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "bonding_requirement",
    category: "indemnification_insurance",
    pattern: /(performance bond|bid bond|parent company guarantee|warranty bond|maintenance bond)/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Bonding requirement found.",
    whyItMatters: "Bonding capacity and cost affect bid feasibility and cash flow.",
    legalExposure: "Bonding cost and capacity commitment for the contract duration.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 4. Warranty & defects
  {
    clauseType: "defects_liability_period",
    category: "warranty_defects",
    pattern: /(defects liability period|latent defect)/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Defects liability / latent defect period clause found.",
    whyItMatters: "Latent defects liability can extend years beyond practical completion.",
    legalExposure: "Extended warranty exposure beyond the stated defects liability period.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "fitness_for_purpose",
    category: "warranty_defects",
    pattern: /fit(?:ness)? for purpose/i,
    severity: "high",
    confidence: 0.7,
    summary: "Fitness-for-purpose warranty standard found.",
    whyItMatters: "Fitness-for-purpose is uninsurable under most professional indemnity policies — a material flag.",
    legalExposure: "Warranty standard likely falls outside PI insurance coverage.",
    companyPosition: "Standard company policy accepts reasonable-skill-and-care warranties only, not fitness-for-purpose.",
    recommendedAction: "escalate_to_counsel",
    requiresExternalCounsel: true,
  },

  // 5. Termination & suspension
  {
    clauseType: "termination_for_convenience",
    category: "termination_suspension",
    pattern: /termination for convenience/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Termination-for-convenience clause found — confirm notice period and compensation.",
    whyItMatters: "Owner's ability to terminate without cause affects revenue certainty and demobilization cost recovery.",
    legalExposure: "Loss of expected revenue on termination, limited to whatever compensation the clause provides.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "termination_for_cause",
    category: "termination_suspension",
    pattern: /termination for (?:default|cause)/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Termination-for-cause clause found — confirm cure periods and consequences.",
    whyItMatters: "Default triggers and cure periods determine how much room the bidder has before losing the contract.",
    legalExposure: "Risk of default declaration and owner completing the works using the contractor's plant/materials.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "suspension_rights",
    category: "termination_suspension",
    pattern: /(right to suspend|suspension of the works)/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Owner suspension right found — confirm compensation for suspension-caused delay/cost.",
    whyItMatters: "Uncompensated suspension shifts delay/cost risk to the bidder.",
    legalExposure: "Potential uncompensated delay and cost during any owner-directed suspension.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 6. Change management & claims
  {
    clauseType: "notice_condition_precedent",
    category: "change_management_claims",
    pattern: /condition precedent|notice.{0,40}within\s+\d+\s+days/i,
    severity: "high",
    confidence: 0.7,
    summary: "Notice deadline operating as a condition precedent to claims.",
    whyItMatters: "Missing this deadline can forfeit the entitlement entirely — one of the most consequential and most-missed clause types in construction contracts.",
    legalExposure: "Loss of claim entitlement if the notice deadline is missed, regardless of merit.",
    recommendedAction: "negotiate_before_bid",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "variation_procedure",
    category: "change_management_claims",
    pattern: /(variation order|change order procedure)/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Change order / variation procedure found.",
    whyItMatters: "The valuation method for variations affects how change is priced and paid.",
    legalExposure: "Under-recovery risk if the valuation method is unfavorable.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "extension_of_time",
    category: "change_management_claims",
    pattern: /extension of time/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Extension-of-time entitlement clause found.",
    whyItMatters: "EOT mechanism determines whether schedule relief is available for owner-caused delay.",
    legalExposure: "LD exposure if EOT entitlement is narrow or the claim mechanism is missed.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 7. Dispute resolution & governing law
  {
    clauseType: "governing_law",
    category: "dispute_resolution_governing_law",
    pattern: /governing law/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Governing law clause found — confirm against the bidder's home jurisdiction.",
    whyItMatters: "A governing-law mismatch with the bidder's home jurisdiction affects enforceability and dispute cost.",
    legalExposure: "Potential unfamiliar legal regime governing contract interpretation and remedies.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "arbitration",
    category: "dispute_resolution_governing_law",
    pattern: /(arbitration|arbitral tribunal)/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Arbitration clause found — confirm seat/venue.",
    whyItMatters: "Seat and venue affect dispute cost and procedural rules that apply.",
    legalExposure: "Dispute cost and procedural exposure tied to the stated seat/venue.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "statutory_adjudication",
    category: "dispute_resolution_governing_law",
    pattern: /(statutory adjudication|construction act)/i,
    severity: "low",
    confidence: 0.5,
    summary: "Statutory adjudication reference found.",
    whyItMatters: "Contract may attempt to restrict a statutory adjudication right — worth flagging even where unenforceable.",
    legalExposure: "Low — informational unless the restriction is later relied upon.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 8. Compliance & eligibility to bid
  {
    clauseType: "mandatory_joint_venture",
    category: "compliance_eligibility",
    pattern: /mandatory joint venture|shall (?:form|enter into) a joint venture with a local|JV with a local partner is mandatory/i,
    severity: "critical",
    criticalFlag: "JOINT_VENTURE_REQUIREMENT",
    confidence: 0.7,
    summary: "Tender mandates a joint venture / local partner.",
    whyItMatters: "A mandatory JV requirement places qualification burden on the JV as a whole and needs a partner secured before bid.",
    legalExposure: "Bid ineligibility if no qualifying JV partner is secured before submission.",
    recommendedAction: "escalate_to_counsel",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "blacklisting_declaration_broad_wording",
    category: "compliance_eligibility",
    pattern: /no dispute with any government (?:entity|department|authority)/i,
    severity: "critical",
    criticalFlag: "BLACKLISTING_DECLARATION_ISSUE",
    confidence: 0.6,
    summary: "Blacklisting/debarment declaration uses overly broad wording.",
    whyItMatters: "Overly broad declaration wording (e.g. 'no dispute with any government entity') can create exposure even for legitimate, unrelated disputes.",
    legalExposure: "Risk of an untruthful declaration, or bid disqualification, depending on the bidder's dispute history.",
    recommendedAction: "escalate_to_counsel",
    requiresExternalCounsel: true,
  },
  {
    clauseType: "blacklisting_declaration",
    category: "compliance_eligibility",
    pattern: /(blacklist(?:ed|ing)? declaration|debarment declaration)/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Blacklisting/debarment declaration required.",
    whyItMatters: "Confirm the required declaration is one the bidder can truthfully sign.",
    legalExposure: "Bid disqualification if the declaration cannot be truthfully signed.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "local_content_requirement",
    category: "compliance_eligibility",
    pattern: /(local content requirement|domestic content requirement|minimum\s+\d+%\s+local\s+(?:labou?r|material))/i,
    severity: "medium",
    confidence: 0.6,
    summary: "Local/domestic content requirement found.",
    whyItMatters: "A minimum local labor, material, or subcontracting percentage affects bid structure and cost.",
    legalExposure: "Bid non-compliance risk if the local content threshold can't be met.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "license_registration_prerequisite",
    category: "compliance_eligibility",
    pattern: /(valid licen[cs]e|professional accreditation|registration with)/i,
    severity: "low",
    confidence: 0.5,
    summary: "Licensing/registration prerequisite found — confirm the bidder holds it.",
    whyItMatters: "Missing a required license or registration is grounds for bid rejection.",
    legalExposure: "Bid ineligibility if the prerequisite isn't held at submission.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "bid_validity_period",
    category: "compliance_eligibility",
    pattern: /bid (?:shall remain )?valid(?:ity period)?/i,
    severity: "low",
    confidence: 0.45,
    summary: "Bid validity period clause found.",
    whyItMatters: "Bid-bond forfeiture conditions may attach to withdrawal within the validity period.",
    legalExposure: "Bid-bond forfeiture risk if withdrawn within the stated validity period.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 9. IP, confidentiality & assignment
  {
    clauseType: "confidentiality_nda",
    category: "ip_confidentiality_assignment",
    pattern: /(confidentiality agreement|non-disclosure)/i,
    severity: "low",
    confidence: 0.5,
    summary: "Confidentiality/NDA clause found.",
    whyItMatters: "Confirm data handling obligations are workable for the bidder's own systems.",
    legalExposure: "Contractual exposure for confidentiality breach, including by subcontractors.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "ip_ownership",
    category: "ip_confidentiality_assignment",
    pattern: /intellectual property.{0,40}(?:owned by|vests in|shall belong to) the (?:owner|employer)/i,
    severity: "medium",
    confidence: 0.6,
    summary: "IP ownership assigned to the owner/employer.",
    whyItMatters: "Confirm license-back rights exist if the bidder needs to reuse its own design IP elsewhere.",
    legalExposure: "Loss of reuse rights to deliverables created under the contract.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "assignment_restriction",
    category: "ip_confidentiality_assignment",
    pattern: /shall not assign.{0,40}without.{0,20}consent/i,
    severity: "low",
    confidence: 0.5,
    summary: "Assignment restriction requiring consent found.",
    whyItMatters: "Affects the bidder's ability to assign or subcontract portions of the work.",
    legalExposure: "Low — standard consent-based restriction unless consent is unreasonably withheld.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },

  // 10. Third-party & step-in arrangements
  {
    clauseType: "collateral_warranty",
    category: "third_party_step_in",
    pattern: /collateral warrant(?:y|ies)/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Collateral warranty obligation found.",
    whyItMatters: "Collateral warranties extend contractual duties to funders, purchasers, or other third parties beyond the direct contract.",
    legalExposure: "Extended duty of care to named third-party beneficiaries.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
  {
    clauseType: "step_in_rights",
    category: "third_party_step_in",
    pattern: /step-?in right/i,
    severity: "medium",
    confidence: 0.55,
    summary: "Step-in rights clause found.",
    whyItMatters: "A funder's right to step in changes who the bidder answers to mid-contract.",
    legalExposure: "Counterparty risk if a funder steps in under different terms or creditworthiness.",
    recommendedAction: "note_only",
    requiresExternalCounsel: false,
  },
];
